[build]
  publish = "public"

[[edge_functions]]
  function = "trap"
  path = "/r/*"

[[edge_functions]]
  function = "scrape"
  path = "/api/scrape"

[[edge_functions]]
  function = "upload"
  path = "/api/upload"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"

